ALTER TABLE Person /*FOREIGN KEY CONSTRAINTS*/
ADD CONSTRAINT FK_Physicall_Address
FOREIGN KEY (Physical_Address) REFERENCES Residence(Physical_Address)
ON DELETE CASCADE
ON UPDATE CASCADE
/*CASCADING EFFECTS THE SPECIFIC FK ALL OVER THE DATABASE WHERE IT IS PRESENT*/
;

ALTER TABLE SystemAdmin /**/
ADD CONSTRAINT FK_ID_Number
FOREIGN KEY (ID_Number) REFERENCES Person(ID_Number)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Attendee /**/
ADD CONSTRAINT FK_Business_Reg_No
FOREIGN KEY (Business_Reg_No) REFERENCES BusinessInfo(Business_Reg_No)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Attendee /**/
ADD CONSTRAINT FK_Notification_No
FOREIGN KEY (Notification_No) REFERENCES Notification_(Notification_No)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Registration /**/
ADD CONSTRAINT FK_Attendee_ID
FOREIGN KEY (Attendee_ID) REFERENCES Attendee(Attendee_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Event_ /**/
ADD CONSTRAINT FK_Reg_ID
FOREIGN KEY (Reg_ID) REFERENCES Registration(Reg_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Category /**/
ADD CONSTRAINT FK_Event_ID
FOREIGN KEY (Event_ID) REFERENCES Event_(Event_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Authentication_ /**/
ADD CONSTRAINT FK_Attendee_ID_2
FOREIGN KEY (Attendee_ID) REFERENCES Attendee(Attendee_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Authentication_ /**/
ADD CONSTRAINT FK_Staff_ID
FOREIGN KEY (Staff_ID) REFERENCES SystemAdmin(Staff_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Transaction_ /**/
ADD CONSTRAINT FK_Payment_No
FOREIGN KEY (Payment_No) REFERENCES Event_Payment(Payment_No)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Transaction_ /**/
ADD CONSTRAINT FK_Bank_Card_Number
FOREIGN KEY (Bank_Card_Number) REFERENCES Bank_Card(Bank_Card_Number)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Bank_Card /**/
ADD CONSTRAINT FK_Attendee_ID_3
FOREIGN KEY (Attendee_ID) REFERENCES Attendee(Attendee_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Event_Payment /**/
ADD CONSTRAINT FK_Event_ID_2
FOREIGN KEY (Event_ID) REFERENCES Event_(Event_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Event_Payment /**/
ADD CONSTRAINT FK_Bank_Card_Number_2
FOREIGN KEY (Bank_Card_Number) REFERENCES Bank_Card(Bank_Card_Number)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Event_Payment /**/
ADD CONSTRAINT FK_Attendee_ID_4
FOREIGN KEY (Attendee_ID) REFERENCES Attendee(Attendee_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Notification_ /**/
ADD CONSTRAINT FK_Staff_ID_2
FOREIGN KEY (Staff_ID) REFERENCES SystemAdmin(Staff_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE SystemAdmin /**/
ADD CONSTRAINT FK_Auth_Password
FOREIGN KEY (Auth_Password) REFERENCES Authentication_(Auth_Password)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE Attendee /**/
ADD CONSTRAINT FK_Auth_Password_2
FOREIGN KEY (Auth_Password) REFERENCES Authentication_(Auth_Password)
ON DELETE CASCADE
ON UPDATE CASCADE
;
